name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish -c Release -o out

    - name: Build Docker image
      run: docker build -t devops-demo-api .

    # Check if secrets exist
    - name: Verify Docker Hub secrets
      run: |
        if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
          echo "ERROR: DOCKERHUB_USERNAME secret is missing!"
          exit 1
        fi
        if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
          echo "ERROR: DOCKERHUB_TOKEN secret is missing!"
          exit 1
        fi
        echo "Secrets exist, proceeding with Docker login"

    # Docker login
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Push Docker image
    - name: Push image to Docker Hub
      run: |
        docker tag devops-demo-api ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo-api:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo-api:latest
